/**
 * @file tst_orgbackend_external.cpp
 * @brief External reference tests for OrgBackend.
 *
 * Migrated from PlanStan/tests/backends/ (G.9.b Tasks 68-69).
 * Rewrote storeItems/loadItems → pushItems/fetchItems (operation API).
 *
 * These tests use HANDWRITTEN org-mode content based on org-mode documentation,
 * NOT content generated by OrgBackend itself. This avoids self-referential
 * testing where bugs in serialization and parsing cancel each other out.
 *
 * Test categories:
 * 1. Parse Tests: Known org-mode input → expected KCalendarCore fields
 * 2. Serialize Tests: Known KCalendarCore data → expected org-mode output
 * 3. Edge Cases: Unusual but valid org-mode constructs
 *
 * Reference: https://orgmode.org/manual/
 */

#include <QtTest>
#include <QTemporaryDir>
#include <QFile>
#include <QRegularExpression>
#include <KCalendarCore/MemoryCalendar>
#include <KCalendarCore/Event>
#include <KCalendarCore/Todo>
#include "orgbackend.h"
#include "syncoperation.h"

using namespace Kalburator::Sync;


class OrgBackendExternalTest : public QObject
{
    Q_OBJECT

private slots:
    void initTestCase();
    void cleanupTestCase();

    // =========================================================================
    // PARSE TESTS: Known org-mode input → expected KCalendarCore fields
    // =========================================================================

    // Basic headline parsing
    void testParseSimpleTodoHeadline();
    void testParseEventHeadline();
    void testParseDoneKeyword();
    void testParseInProgressKeyword();

    // Priority parsing (org-mode [#A], [#B], [#C])
    void testParsePriorityA();
    void testParsePriorityB();
    void testParsePriorityC();

    // Timestamp parsing (org-mode <YYYY-MM-DD Day HH:MM>)
    void testParseScheduledTimestamp();
    void testParseDeadlineTimestamp();
    void testParseClosedTimestamp();
    void testParseAllDayTimestamp();
    void testParseTimestampWithTime();

    // Property drawer parsing
    void testParseIdProperty();
    void testParseLocationProperty();
    void testParseUrlProperty();
    void testParseGeoProperty();
    void testParseClassProperty();
    void testParseCreatedProperty();
    void testParseLastModifiedProperty();

    // Description/body parsing
    void testParseBodyAsDescription();
    void testParseMultilineDescription();

    // Repeater parsing (org-mode +1w, ++1d, .+1m)
    void testParseSimpleRepeater();
    void testParseCatchUpRepeater();
    void testParseRestartRepeater();

    // =========================================================================
    // SERIALIZE TESTS: Known KCalendarCore data → expected org-mode output
    // =========================================================================

    void testSerializeTodoKeyword();
    void testSerializeDoneKeyword();
    void testSerializePriorityA();
    void testSerializeScheduledWithTime();
    void testSerializeDeadlineWithTime();
    void testSerializePropertyDrawer();
    void testSerializeDescription();
    void testSerializeWeeklyRepeater();

    // =========================================================================
    // EDGE CASES: Unusual but valid org-mode constructs
    // =========================================================================

    void testParseHeadlineWithTags();
    void testParseNestedHeadlines();
    void testParseNoPropertyDrawer();
    void testParseEmptyPropertyDrawer();
    void testParsePropertyWithSpaces();
    void testParseUnicodeContent();

    // =========================================================================
    // INTEROPERABILITY: Files that might come from real Emacs org-mode
    // =========================================================================

    void testParseEmacsStyleOrgFile();
    void testParseMobileOrgStyle();

    // =========================================================================
    // CUSTOM #+TODO: KEYWORD TESTS
    // =========================================================================

    void testParseCustomTodoKeyword();
    void testDefaultKeywordSequence();
    void testKeywordRoundtrip();

    // =========================================================================
    // BODY CONTENT PRESERVATION (Phase 5)
    // =========================================================================

    void testSourceBlockSurvivesRoundtrip();
    void testTableSurvivesRoundtrip();
    void testCheckboxesSurviveRoundtrip();
    void testLogbookDrawerSurvivesRoundtrip();
    void testDescriptionChangePreservesStructural();
    void testMultilineDescriptionRoundtrip();
    void testOrgzlyStyleRoundtrip();

    // =========================================================================
    // STRINGENT FORMAT VERIFICATION (likely to catch bugs)
    // =========================================================================

    void testSerializeExactTodoFormat();
    void testSerializeExactPriorityFormat();
    void testSerializeTimestampHasDayOfWeek();
    void testSerializeClosedTimestamp();
    void testTagsParsedAsCategories();
    void testActiveVsInactiveTimestamp();
    void testDateRangeTimestamp();
    void testTimeRangeTimestamp();
    void testPercentComplete();
    void testEffortProperty();

private:
    // Creates a .org file with the given content, returns the calendarId (filename without .org)
    QString createOrgFile(const QString &content);

    // Loads items from org content into calendar via fetchItems
    QList<KCalendarCore::Incidence::Ptr> loadFromOrgContent(const QString &content);

    // Serializes all calendar incidences to org and returns the file content
    QString serializeToOrg(KCalendarCore::MemoryCalendar *calendar, const QString &calendarId);

    // Find incidence by UID in a list
    KCalendarCore::Incidence::Ptr findByUid(const QList<KCalendarCore::Incidence::Ptr> &items,
                                             const QString &uid) const;

    QTemporaryDir *m_tempDir = nullptr;
};

void OrgBackendExternalTest::initTestCase()
{
    m_tempDir = new QTemporaryDir();
    QVERIFY2(m_tempDir->isValid(), "Failed to create temp directory");
}

void OrgBackendExternalTest::cleanupTestCase()
{
    delete m_tempDir;
    m_tempDir = nullptr;
}

QString OrgBackendExternalTest::createOrgFile(const QString &content)
{
    static int fileCounter = 0;
    QString fileName = QString(QStringLiteral("test%1.org")).arg(++fileCounter);
    QString filePath = m_tempDir->filePath(fileName);

    QFile file(filePath);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        file.write(content.toUtf8());
        file.close();
    }

    return fileName.replace(QStringLiteral(".org"), QString());  // Return calendar ID
}

QList<KCalendarCore::Incidence::Ptr> OrgBackendExternalTest::loadFromOrgContent(const QString &content)
{
    QString calendarId = createOrgFile(content);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);
    return fetchOp->fetchedItems();
}

QString OrgBackendExternalTest::serializeToOrg(KCalendarCore::MemoryCalendar *calendar,
                                                const QString &calendarId)
{
    OrgBackend backend(m_tempDir->path());
    backend.createCalendar(QString(), calendarId, calendarId);

    QList<KCalendarCore::Incidence::Ptr> items;
    for (const auto &inc : calendar->incidences()) {
        items.append(inc);
    }

    auto *op = backend.pushItems(calendarId, items, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(op->isFinished(), 5000);
    QCOMPARE(op->state(), SyncOperation::Succeeded);

    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    if (file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return QString::fromUtf8(file.readAll());
    }
    return QString();
}

KCalendarCore::Incidence::Ptr OrgBackendExternalTest::findByUid(
    const QList<KCalendarCore::Incidence::Ptr> &items, const QString &uid) const
{
    for (const auto &inc : items) {
        if (inc->uid() == uid)
            return inc;
    }
    return {};
}

// =============================================================================
// PARSE TESTS
// =============================================================================

void OrgBackendExternalTest::testParseSimpleTodoHeadline()
{
    const QString orgContent = QStringLiteral("* TODO Buy groceries\n");

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->type() == KCalendarCore::Incidence::TypeTodo);
    QCOMPARE(inc->summary(), QStringLiteral("Buy groceries"));

    auto todo = inc.dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);
    QVERIFY(!todo->isCompleted());
}

void OrgBackendExternalTest::testParseEventHeadline()
{
    // Headline without TODO keyword is still a Todo (all org headlines are todos)
    const QString orgContent = QStringLiteral(
        "* Meeting with Bob\n"
        "  SCHEDULED: <2024-03-15 Fri 10:00>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->type() == KCalendarCore::Incidence::TypeTodo);
    QCOMPARE(inc->summary(), QStringLiteral("Meeting with Bob"));
}

void OrgBackendExternalTest::testParseDoneKeyword()
{
    const QString orgContent = QStringLiteral(
        "* DONE Complete report\n"
        "  CLOSED: [2024-03-10 Sun 15:30]\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto todo = items.first().dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);
    QCOMPARE(todo->summary(), QStringLiteral("Complete report"));
    QVERIFY2(todo->isCompleted(), "DONE keyword should set isCompleted=true");
}

void OrgBackendExternalTest::testParseInProgressKeyword()
{
    const QString orgContent = QStringLiteral("* INPROGRESS Write documentation\n");

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto todo = items.first().dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);
    QCOMPARE(todo->summary(), QStringLiteral("Write documentation"));
    QCOMPARE(todo->status(), KCalendarCore::Todo::StatusInProcess);
}

void OrgBackendExternalTest::testParsePriorityA()
{
    const QString orgContent = QStringLiteral("* TODO [#A] Urgent task\n");

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->summary(), QStringLiteral("Urgent task"));
    QCOMPARE(inc->priority(), 1);
}

void OrgBackendExternalTest::testParsePriorityB()
{
    const QString orgContent = QStringLiteral("* TODO [#B] Normal task\n");

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->summary(), QStringLiteral("Normal task"));
    QCOMPARE(inc->priority(), 5);
}

void OrgBackendExternalTest::testParsePriorityC()
{
    const QString orgContent = QStringLiteral("* TODO [#C] Low priority task\n");

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->summary(), QStringLiteral("Low priority task"));
    QCOMPARE(inc->priority(), 9);
}

void OrgBackendExternalTest::testParseScheduledTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with schedule\n"
        "  SCHEDULED: <2024-06-15 Sat 14:30>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->dtStart().isValid());
    QCOMPARE(inc->dtStart().date(), QDate(2024, 6, 15));
    QCOMPARE(inc->dtStart().time(), QTime(14, 30));
}

void OrgBackendExternalTest::testParseDeadlineTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with deadline\n"
        "  DEADLINE: <2024-07-20 Sat 17:00>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto todo = items.first().dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);
    QVERIFY(todo->dtDue().isValid());
    QCOMPARE(todo->dtDue().date(), QDate(2024, 7, 20));
    QCOMPARE(todo->dtDue().time(), QTime(17, 0));
}

void OrgBackendExternalTest::testParseClosedTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* DONE Completed task\n"
        "  CLOSED: [2024-05-10 Fri 11:45]\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto todo = items.first().dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);
    QVERIFY(todo->isCompleted());
    QVERIFY(todo->completed().isValid());
    QCOMPARE(todo->completed().date(), QDate(2024, 5, 10));
}

void OrgBackendExternalTest::testParseAllDayTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* TODO All day event\n"
        "  SCHEDULED: <2024-08-01 Thu>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->dtStart().isValid());
    QCOMPARE(inc->dtStart().date(), QDate(2024, 8, 1));
    QVERIFY2(inc->allDay(), "Timestamp without time should be all-day");
}

void OrgBackendExternalTest::testParseTimestampWithTime()
{
    const QString orgContent = QStringLiteral(
        "* TODO Timed event\n"
        "  SCHEDULED: <2024-08-01 Thu 09:00>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->dtStart().isValid());
    QCOMPARE(inc->dtStart().time(), QTime(9, 0));
    QVERIFY2(!inc->allDay(), "Timestamp with time should NOT be all-day");
}

void OrgBackendExternalTest::testParseIdProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with ID\n"
        "  :PROPERTIES:\n"
        "  :ID:       abc123-def456-ghi789\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->uid(), QStringLiteral("abc123-def456-ghi789"));
}

void OrgBackendExternalTest::testParseLocationProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Meeting\n"
        "  :PROPERTIES:\n"
        "  :ID:       loc-test-123\n"
        "  :LOCATION: Conference Room 101\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->location(), QStringLiteral("Conference Room 101"));
}

void OrgBackendExternalTest::testParseUrlProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Check website\n"
        "  :PROPERTIES:\n"
        "  :ID:       url-test-123\n"
        "  :URL:      https://example.com/project\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->url(), QUrl(QStringLiteral("https://example.com/project")));
}

void OrgBackendExternalTest::testParseGeoProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Visit location\n"
        "  :PROPERTIES:\n"
        "  :ID:       geo-test-123\n"
        "  :GEO:      37.774900;-122.419400\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->hasGeo());
    QVERIFY(qAbs(inc->geoLatitude() - 37.7749f) < 0.001f);
    QVERIFY(qAbs(inc->geoLongitude() - (-122.4194f)) < 0.001f);
}

void OrgBackendExternalTest::testParseClassProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Private task\n"
        "  :PROPERTIES:\n"
        "  :ID:       class-test-123\n"
        "  :CLASS:    PRIVATE\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->secrecy(), KCalendarCore::Incidence::SecrecyPrivate);
}

void OrgBackendExternalTest::testParseCreatedProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with creation date\n"
        "  :PROPERTIES:\n"
        "  :ID:       created-test-123\n"
        "  :CREATED:  <2024-01-15 Mon 10:30>\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->created().isValid());
    QCOMPARE(inc->created().date(), QDate(2024, 1, 15));
}

void OrgBackendExternalTest::testParseLastModifiedProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with modification date\n"
        "  :PROPERTIES:\n"
        "  :ID:           lastmod-test-123\n"
        "  :LAST-MODIFIED: <2024-02-20 Tue 14:45>\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->lastModified().isValid());
    QCOMPARE(inc->lastModified().date(), QDate(2024, 2, 20));
}

void OrgBackendExternalTest::testParseBodyAsDescription()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with description\n"
        "  :PROPERTIES:\n"
        "  :ID:       desc-test-123\n"
        "  :END:\n"
        "  This is the task description.\n"
        "  It explains what needs to be done.\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY2(inc->description().contains(QStringLiteral("task description")),
             qPrintable(QStringLiteral("Description should contain body text: ") + inc->description()));
}

void OrgBackendExternalTest::testParseMultilineDescription()
{
    const QString orgContent = QStringLiteral(
        "* TODO Multi-line task\n"
        "  :PROPERTIES:\n"
        "  :ID:       multiline-123\n"
        "  :END:\n"
        "  Line one of description.\n"
        "  Line two of description.\n"
        "  Line three of description.\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->description().contains(QStringLiteral("Line one")));
    QVERIFY(inc->description().contains(QStringLiteral("Line two")));
    QVERIFY(inc->description().contains(QStringLiteral("Line three")));
}

void OrgBackendExternalTest::testParseSimpleRepeater()
{
    const QString orgContent = QStringLiteral(
        "* TODO Weekly meeting\n"
        "  SCHEDULED: <2024-01-15 Mon 10:00 +1w>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY2(inc->recurs(), "Item with +1w repeater should have recurrence");

    auto recurrence = inc->recurrence();
    QCOMPARE(recurrence->recurrenceType(), static_cast<ushort>(KCalendarCore::Recurrence::rWeekly));
    QCOMPARE(recurrence->frequency(), 1);
}

void OrgBackendExternalTest::testParseCatchUpRepeater()
{
    const QString orgContent = QStringLiteral(
        "* TODO Bill payment\n"
        "  SCHEDULED: <2024-01-15 Mon ++1w>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY2(inc->recurs(), "Item with ++1w repeater should have recurrence");

    // Under incidence purity (Feb 2026), repeater syntax is NOT on the incidence.
    // It lives in OrgBackend's private roundtrip data. The incidence just has
    // standard KCalendarCore recurrence (weekly, frequency=1).
    QVERIFY2(inc->customProperty("PLANSTAN", "X-ORG-REPEATER").isEmpty(),
             "Repeater syntax should NOT be on incidence under incidence purity model");
}

void OrgBackendExternalTest::testParseRestartRepeater()
{
    const QString orgContent = QStringLiteral(
        "* TODO Monthly review\n"
        "  SCHEDULED: <2024-01-15 Mon .+1m>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY2(inc->recurs(), "Item with .+1m repeater should have recurrence");

    // Under incidence purity (Feb 2026), repeater syntax is NOT on the incidence.
    QVERIFY2(inc->customProperty("PLANSTAN", "X-ORG-REPEATER").isEmpty(),
             "Repeater syntax should NOT be on incidence under incidence purity model");
}

// =============================================================================
// SERIALIZE TESTS
// =============================================================================

void OrgBackendExternalTest::testSerializeTodoKeyword()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-todo-123"));
    todo->setSummary(QStringLiteral("Test Todo"));
    todo->setStatus(KCalendarCore::Todo::StatusNeedsAction);
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-todo-test"));

    QVERIFY2(content.contains(QStringLiteral("TODO")),
             qPrintable(QStringLiteral("Output should contain TODO keyword: ") + content));
    QVERIFY(content.contains(QStringLiteral("Test Todo")));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeDoneKeyword()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-done-123"));
    todo->setSummary(QStringLiteral("Completed Todo"));
    todo->setCompleted(true);
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-done-test"));

    QVERIFY2(content.contains(QStringLiteral("DONE")),
             qPrintable(QStringLiteral("Output should contain DONE keyword: ") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializePriorityA()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-priority-123"));
    todo->setSummary(QStringLiteral("High Priority"));
    todo->setPriority(1);
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-priority-test"));

    QVERIFY2(content.contains(QStringLiteral("[#A]")),
             qPrintable(QStringLiteral("Priority 1 should serialize as [#A]: ") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeScheduledWithTime()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-sched-123"));
    todo->setSummary(QStringLiteral("Scheduled Todo"));
    todo->setDtStart(QDateTime(QDate(2024, 6, 15), QTime(14, 30)));
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-sched-test"));

    QVERIFY2(content.contains(QStringLiteral("SCHEDULED:")),
             qPrintable(QStringLiteral("Output should contain SCHEDULED: ") + content));
    QVERIFY2(content.contains(QStringLiteral("2024-06-15")),
             qPrintable(QStringLiteral("Output should contain date: ") + content));
    QVERIFY2(content.contains(QStringLiteral("14:30")),
             qPrintable(QStringLiteral("Output should contain time 14:30: ") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeDeadlineWithTime()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-deadline-123"));
    todo->setSummary(QStringLiteral("Todo with Deadline"));
    todo->setDtDue(QDateTime(QDate(2024, 7, 20), QTime(17, 0)));
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-deadline-test"));

    QVERIFY2(content.contains(QStringLiteral("DEADLINE:")),
             qPrintable(QStringLiteral("Output should contain DEADLINE: ") + content));
    QVERIFY2(content.contains(QStringLiteral("2024-07-20")),
             qPrintable(QStringLiteral("Output should contain date: ") + content));
    QVERIFY2(content.contains(QStringLiteral("17:00")),
             qPrintable(QStringLiteral("Output should contain time 17:00: ") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializePropertyDrawer()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-props-123"));
    todo->setSummary(QStringLiteral("Todo with Properties"));
    todo->setLocation(QStringLiteral("Room 101"));
    todo->setUrl(QUrl(QStringLiteral("https://example.com")));
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-props-test"));

    QVERIFY2(content.contains(QStringLiteral(":PROPERTIES:")),
             qPrintable(QStringLiteral("Output should contain :PROPERTIES:: ") + content));
    QVERIFY2(content.contains(QStringLiteral(":END:")),
             qPrintable(QStringLiteral("Output should contain :END:: ") + content));
    QVERIFY2(content.contains(QStringLiteral(":ID:")),
             qPrintable(QStringLiteral("Output should contain :ID:: ") + content));
    QVERIFY2(content.contains(QStringLiteral(":LOCATION:")),
             qPrintable(QStringLiteral("Output should contain :LOCATION:: ") + content));
    QVERIFY2(content.contains(QStringLiteral(":URL:")),
             qPrintable(QStringLiteral("Output should contain :URL:: ") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeDescription()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-desc-123"));
    todo->setSummary(QStringLiteral("Todo with Description"));
    todo->setDescription(QStringLiteral("This is the task description.\nWith multiple lines."));
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-desc-test"));

    QVERIFY2(content.contains(QStringLiteral("task description")),
             qPrintable(QStringLiteral("Output should contain description text: ") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeWeeklyRepeater()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("serialize-repeat-123"));
    todo->setSummary(QStringLiteral("Weekly Todo"));
    todo->setDtStart(QDateTime(QDate(2024, 1, 15), QTime(10, 0)));
    todo->recurrence()->setWeekly(1);
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("serialize-repeat-test"));

    QVERIFY2(content.contains(QStringLiteral("+1w")),
             qPrintable(QStringLiteral("Weekly recurrence should serialize as +1w: ") + content));

    delete calendar;
}

// =============================================================================
// EDGE CASES
// =============================================================================

void OrgBackendExternalTest::testParseHeadlineWithTags()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with tags                                     :work:urgent:\n"
        "  :PROPERTIES:\n"
        "  :ID:       tags-test-123\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY2(!inc->summary().contains(QStringLiteral(":work:")),
             qPrintable(QStringLiteral("Summary should not contain tags: ") + inc->summary()));
}

void OrgBackendExternalTest::testParseNestedHeadlines()
{
    const QString orgContent = QStringLiteral(
        "* TODO Parent task\n"
        "  :PROPERTIES:\n"
        "  :ID:       parent-123\n"
        "  :END:\n"
        "** TODO Child task\n"
        "   :PROPERTIES:\n"
        "   :ID:       child-456\n"
        "   :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QVERIFY2(items.size() >= 1,
             qPrintable(QString(QStringLiteral("Expected at least 1 incidence, got %1")).arg(items.size())));
}

void OrgBackendExternalTest::testParseNoPropertyDrawer()
{
    const QString orgContent = QStringLiteral("* TODO Simple task without properties\n");

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->summary(), QStringLiteral("Simple task without properties"));
    QVERIFY2(!inc->uid().isEmpty(), "Auto-generated UID expected");
}

void OrgBackendExternalTest::testParseEmptyPropertyDrawer()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with empty drawer\n"
        "  :PROPERTIES:\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->summary(), QStringLiteral("Task with empty drawer"));
}

void OrgBackendExternalTest::testParsePropertyWithSpaces()
{
    const QString orgContent = QStringLiteral(
        "* TODO Meeting\n"
        "  :PROPERTIES:\n"
        "  :ID:       spaces-test-123\n"
        "  :LOCATION: Building A, Floor 3, Room 101\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->location(), QStringLiteral("Building A, Floor 3, Room 101"));
}

void OrgBackendExternalTest::testParseUnicodeContent()
{
    const QString orgContent = QString::fromUtf8(
        "* TODO 日本語タスク\n"
        "  :PROPERTIES:\n"
        "  :ID:       unicode-test-123\n"
        "  :LOCATION: 東京オフィス\n"
        "  :END:\n"
        "  Description with émojis: 🎉✨\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->summary(), QString::fromUtf8("日本語タスク"));
    QCOMPARE(inc->location(), QString::fromUtf8("東京オフィス"));
}

// =============================================================================
// INTEROPERABILITY
// =============================================================================

void OrgBackendExternalTest::testParseEmacsStyleOrgFile()
{
    const QString orgContent = QStringLiteral(
        "#+TITLE: My Tasks\n"
        "#+STARTUP: overview\n"
        "\n"
        "* Projects\n"
        "** TODO [#A] Complete project proposal                        :work:urgent:\n"
        "   DEADLINE: <2024-03-20 Wed 17:00> SCHEDULED: <2024-03-15 Fri 09:00>\n"
        "   :PROPERTIES:\n"
        "   :ID:       emacs-style-001\n"
        "   :CREATED:  <2024-03-01 Fri 10:30>\n"
        "   :END:\n"
        "   - [ ] Draft outline\n"
        "   - [ ] Write introduction\n"
        "   - [ ] Get feedback\n"
        "\n"
        "** DONE [#B] Review quarterly report                          :work:\n"
        "   CLOSED: [2024-03-10 Sun 16:45]\n"
        "   :PROPERTIES:\n"
        "   :ID:       emacs-style-002\n"
        "   :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QVERIFY2(items.size() >= 2,
             qPrintable(QString(QStringLiteral("Expected at least 2 incidences from Emacs-style file, got %1")).arg(items.size())));

    // Find the DONE item
    auto done = findByUid(items, QStringLiteral("emacs-style-002"));
    if (done) {
        auto todo = done.dynamicCast<KCalendarCore::Todo>();
        if (todo) {
            QVERIFY2(todo->isCompleted(), "DONE item should be completed");
        }
    }
}

void OrgBackendExternalTest::testParseMobileOrgStyle()
{
    const QString orgContent = QStringLiteral(
        "* TODO Quick note from phone\n"
        ":PROPERTIES:\n"
        ":ID: mobileorg-001\n"
        ":END:\n"
        "SCHEDULED: <2024-03-15 Fri>\n"
        "\n"
        "* TODO Another mobile task\n"
        ":PROPERTIES:\n"
        ":ID: mobileorg-002\n"
        ":END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QVERIFY2(items.size() >= 2,
             qPrintable(QString(QStringLiteral("Expected 2 incidences from MobileOrg-style file, got %1")).arg(items.size())));
}

// =============================================================================
// STRINGENT FORMAT VERIFICATION
// =============================================================================

void OrgBackendExternalTest::testSerializeExactTodoFormat()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("exact-todo-123"));
    todo->setSummary(QStringLiteral("Exact Format Test"));
    todo->setStatus(KCalendarCore::Todo::StatusNeedsAction);
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("exact-todo-test"));

    QRegularExpression exactFormat(QStringLiteral(R"(^\* TODO Exact Format Test\s*$)"),
                                   QRegularExpression::MultilineOption);
    QVERIFY2(exactFormat.match(content).hasMatch(),
             qPrintable(QStringLiteral("Headline must be exactly '* TODO Summary', got:\n") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeExactPriorityFormat()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("exact-priority-123"));
    todo->setSummary(QStringLiteral("Priority Format Test"));
    todo->setStatus(KCalendarCore::Todo::StatusNeedsAction);
    todo->setPriority(1);
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("exact-priority-test"));

    QRegularExpression correctOrder(QStringLiteral(R"(^\* TODO \[#A\] Priority Format Test)"),
                                    QRegularExpression::MultilineOption);
    QRegularExpression wrongOrder(QStringLiteral(R"(^\* \[#A\] TODO Priority Format Test)"),
                                  QRegularExpression::MultilineOption);

    QVERIFY2(correctOrder.match(content).hasMatch() || !wrongOrder.match(content).hasMatch(),
             qPrintable(QStringLiteral("Priority must come AFTER TODO keyword: '* TODO [#A] Summary'\nGot:\n") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeTimestampHasDayOfWeek()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("dayofweek-123"));
    todo->setSummary(QStringLiteral("Day of Week Test"));
    // June 15, 2024 is a Saturday
    todo->setDtStart(QDateTime(QDate(2024, 6, 15), QTime(14, 30)));
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("dayofweek-test"));

    QVERIFY2(content.contains(QStringLiteral("Sat")) || content.contains(QStringLiteral("SAT")),
             qPrintable(QStringLiteral("Timestamp must include day-of-week (Sat for 2024-06-15):\n") + content));

    delete calendar;
}

void OrgBackendExternalTest::testSerializeClosedTimestamp()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("closed-format-123"));
    todo->setSummary(QStringLiteral("Closed Format Test"));
    todo->setCompleted(true);
    todo->setCompleted(QDateTime(QDate(2024, 5, 10), QTime(11, 45)));
    calendar->addTodo(todo);

    QString content = serializeToOrg(calendar, QStringLiteral("closed-format-test"));

    QVERIFY2(content.contains(QStringLiteral("CLOSED:")),
             qPrintable(QStringLiteral("Completed todo must have CLOSED: line:\n") + content));

    QRegularExpression inactiveFormat(QStringLiteral(R"(CLOSED:\s*\[\d{4}-\d{2}-\d{2})"));
    QVERIFY2(inactiveFormat.match(content).hasMatch(),
             qPrintable(QStringLiteral("CLOSED timestamp must use inactive format [YYYY-MM-DD...], not <...>:\n") + content));

    delete calendar;
}

void OrgBackendExternalTest::testTagsParsedAsCategories()
{
    const QString orgContent = QStringLiteral(
        "* TODO Tagged task                                         :project:urgent:home:\n"
        "  :PROPERTIES:\n"
        "  :ID:       tags-categories-123\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QStringList cats = inc->categories();

    QVERIFY2(cats.contains(QStringLiteral("project")) || cats.contains(QStringLiteral("PROJECT")),
             qPrintable(QStringLiteral("Tags should be parsed as categories. Got: ") + cats.join(QStringLiteral(", "))));
    QVERIFY2(cats.contains(QStringLiteral("urgent")) || cats.contains(QStringLiteral("URGENT")),
             qPrintable(QStringLiteral("Tags should be parsed as categories. Got: ") + cats.join(QStringLiteral(", "))));
    QVERIFY2(cats.contains(QStringLiteral("home")) || cats.contains(QStringLiteral("HOME")),
             qPrintable(QStringLiteral("Tags should be parsed as categories. Got: ") + cats.join(QStringLiteral(", "))));
}

void OrgBackendExternalTest::testActiveVsInactiveTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* DONE Task with both timestamp types\n"
        "  CLOSED: [2024-03-15 Fri 16:00]\n"
        "  SCHEDULED: <2024-03-10 Sun 09:00>\n"
        "  :PROPERTIES:\n"
        "  :ID:       active-inactive-123\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto todo = items.first().dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);

    QVERIFY2(todo->dtStart().date() == QDate(2024, 3, 10),
             qPrintable(QStringLiteral("SCHEDULED date should be parsed: ") + todo->dtStart().toString()));
    QVERIFY2(todo->completed().date() == QDate(2024, 3, 15),
             qPrintable(QStringLiteral("CLOSED date should be parsed: ") + todo->completed().toString()));
}

void OrgBackendExternalTest::testDateRangeTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* Conference trip\n"
        "  :PROPERTIES:\n"
        "  :ID:       daterange-123\n"
        "  :END:\n"
        "  <2024-01-15 Mon>--<2024-01-17 Wed>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QCOMPARE(inc->dtStart().date(), QDate(2024, 1, 15));
    auto todo = inc.dynamicCast<KCalendarCore::Todo>();
    QVERIFY(todo);
    QVERIFY2(todo->dtDue().date() >= QDate(2024, 1, 17),
             qPrintable(QStringLiteral("Due date should be at least 2024-01-17: ") + todo->dtDue().toString()));
}

void OrgBackendExternalTest::testTimeRangeTimestamp()
{
    const QString orgContent = QStringLiteral(
        "* Meeting\n"
        "  :PROPERTIES:\n"
        "  :ID:       timerange-123\n"
        "  :END:\n"
        "  SCHEDULED: <2024-01-15 Mon 10:00-11:30>\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();
    QVERIFY(inc->type() == KCalendarCore::Incidence::TypeTodo);
    QCOMPARE(inc->dtStart().time(), QTime(10, 0));
}

void OrgBackendExternalTest::testPercentComplete()
{
    auto calendar = new KCalendarCore::MemoryCalendar(QTimeZone::utc());

    auto todo = KCalendarCore::Todo::Ptr::create();
    todo->setUid(QStringLiteral("percent-123"));
    todo->setSummary(QStringLiteral("Percent Complete Test"));
    todo->setPercentComplete(75);
    calendar->addTodo(todo);

    // Use a unique calendar ID so the fetch doesn't conflict with other tests
    const QString calendarId = QStringLiteral("percent-test-unique");
    QString content = serializeToOrg(calendar, calendarId);

    // Reload and verify percent is preserved
    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto reloaded = findByUid(fetchOp->fetchedItems(), QStringLiteral("percent-123"));
    QVERIFY(reloaded);
    auto reloadedTodo = reloaded.dynamicCast<KCalendarCore::Todo>();
    QVERIFY(reloadedTodo);
    QVERIFY2(reloadedTodo->percentComplete() == 75,
             qPrintable(QString(QStringLiteral("Percent complete should be preserved. Expected 75, got %1"))
                        .arg(reloadedTodo->percentComplete())));

    delete calendar;
}

void OrgBackendExternalTest::testEffortProperty()
{
    const QString orgContent = QStringLiteral(
        "* TODO Task with effort estimate\n"
        "  :PROPERTIES:\n"
        "  :ID:       effort-123\n"
        "  :EFFORT:   2:30\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 1);

    auto inc = items.first();

    // Under incidence purity (Feb 2026), EFFORT is NOT stored on the incidence.
    QVERIFY2(inc->customProperty("PLANSTAN", "X-EFFORT").isEmpty(),
             "EFFORT should NOT be on incidence under incidence purity model");

    QCOMPARE(inc->summary(), QStringLiteral("Task with effort estimate"));
}

// =============================================================================
// CUSTOM #+TODO: KEYWORD TESTS
// =============================================================================

void OrgBackendExternalTest::testParseCustomTodoKeyword()
{
    const QString orgContent = QStringLiteral(
        "#+TODO: TODO WAITING | DONE DELEGATED\n"
        "* WAITING Waiting for feedback\n"
        "  :PROPERTIES:\n"
        "  :ID:       custom-kw-123\n"
        "  :END:\n"
        "* DELEGATED Handed off to Bob\n"
        "  :PROPERTIES:\n"
        "  :ID:       custom-kw-456\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 2);

    auto waiting = findByUid(items, QStringLiteral("custom-kw-123"));
    QVERIFY(waiting);
    auto waitingTodo = waiting.dynamicCast<KCalendarCore::Todo>();
    QVERIFY(waitingTodo);
    QCOMPARE(waitingTodo->status(), KCalendarCore::Todo::StatusInProcess);

    auto delegated = findByUid(items, QStringLiteral("custom-kw-456"));
    QVERIFY(delegated);
    auto delegatedTodo = delegated.dynamicCast<KCalendarCore::Todo>();
    QVERIFY(delegatedTodo);
    QCOMPARE(delegatedTodo->status(), KCalendarCore::Todo::StatusCanceled);
}

void OrgBackendExternalTest::testDefaultKeywordSequence()
{
    const QString orgContent = QStringLiteral(
        "* TODO Default task\n"
        "  :PROPERTIES:\n"
        "  :ID:       default-kw-123\n"
        "  :END:\n"
        "* DONE Default completed\n"
        "  :PROPERTIES:\n"
        "  :ID:       default-kw-456\n"
        "  :END:\n"
    );

    auto items = loadFromOrgContent(orgContent);
    QCOMPARE(items.size(), 2);

    auto todo = findByUid(items, QStringLiteral("default-kw-123"));
    QVERIFY(todo);
    QCOMPARE(todo.dynamicCast<KCalendarCore::Todo>()->status(), KCalendarCore::Todo::StatusNeedsAction);

    auto done = findByUid(items, QStringLiteral("default-kw-456"));
    QVERIFY(done);
    QVERIFY(done.dynamicCast<KCalendarCore::Todo>()->isCompleted());
}

void OrgBackendExternalTest::testKeywordRoundtrip()
{
    // WAITING keyword should survive store+reload, not be replaced with INPROGRESS
    const QString orgContent = QStringLiteral(
        "#+TODO: TODO WAITING | DONE DELEGATED\n"
        "* WAITING Needs feedback\n"
        "  :PROPERTIES:\n"
        "  :ID:       kw-roundtrip-123\n"
        "  :END:\n"
    );

    QString calendarId = createOrgFile(orgContent);

    // Load
    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    // Store back
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    // Read file and verify WAITING keyword is preserved
    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("WAITING Needs feedback")),
             qPrintable(QStringLiteral("WAITING keyword should survive roundtrip, got:\n") + content));
    QVERIFY2(!content.contains(QStringLiteral("INPROGRESS")),
             qPrintable(QStringLiteral("INPROGRESS should NOT appear (WAITING was the original keyword):\n") + content));
}

// =============================================================================
// BODY CONTENT PRESERVATION (Phase 5)
// =============================================================================

void OrgBackendExternalTest::testSourceBlockSurvivesRoundtrip()
{
    const QString orgContent = QStringLiteral(
        "* TODO Implement feature\n"
        "  :PROPERTIES:\n"
        "  :ID:       src-block-test-1\n"
        "  :END:\n"
        "Some description text\n"
        "#+BEGIN_SRC python\n"
        "def hello():\n"
        "    print(\"world\")\n"
        "#+END_SRC\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    // Description should contain the prose but NOT the source block
    QVERIFY2(inc->description().contains(QStringLiteral("Some description text")),
             qPrintable(QStringLiteral("Description should contain prose: ") + inc->description()));
    QVERIFY2(!inc->description().contains(QStringLiteral("BEGIN_SRC")),
             qPrintable(QStringLiteral("Description should NOT contain source block markers: ") + inc->description()));

    // Store back (description unchanged)
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    // Read file and verify source block survived
    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("#+BEGIN_SRC python")),
             qPrintable(QStringLiteral("Source block BEGIN should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("def hello():")),
             qPrintable(QStringLiteral("Source block content should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("#+END_SRC")),
             qPrintable(QStringLiteral("Source block END should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("Some description text")),
             qPrintable(QStringLiteral("Description prose should survive roundtrip:\n") + content));
}

void OrgBackendExternalTest::testTableSurvivesRoundtrip()
{
    const QString orgContent = QStringLiteral(
        "* TODO Budget tracker\n"
        "  :PROPERTIES:\n"
        "  :ID:       table-test-1\n"
        "  :END:\n"
        "| Item   | Cost |\n"
        "|--------+------|\n"
        "| Food   |   50 |\n"
        "| Rent   |  800 |\n"
        "|--------+------|\n"
        "|        |  850 |\n"
        "#+TBLFM: @>$2=vsum(@I$2..@II$2)\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    // Store back (description unchanged -- no prose lines here)
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    // Read file and verify table survived
    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("| Item   | Cost |")),
             qPrintable(QStringLiteral("Table header should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("|--------+------|")),
             qPrintable(QStringLiteral("Table separator should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("| Food   |   50 |")),
             qPrintable(QStringLiteral("Table data should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("#+TBLFM:")),
             qPrintable(QStringLiteral("TBLFM formula should survive roundtrip:\n") + content));
}

void OrgBackendExternalTest::testCheckboxesSurviveRoundtrip()
{
    const QString orgContent = QStringLiteral(
        "* TODO Shopping list [1/3]\n"
        "  :PROPERTIES:\n"
        "  :ID:       checkbox-test-1\n"
        "  :END:\n"
        "- [X] Milk\n"
        "- [ ] Eggs\n"
        "- [-] Bread\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    // Store back
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    // Read file and verify checkboxes survived
    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("- [X] Milk")),
             qPrintable(QStringLiteral("Checked checkbox should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("- [ ] Eggs")),
             qPrintable(QStringLiteral("Unchecked checkbox should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("- [-] Bread")),
             qPrintable(QStringLiteral("Undecided checkbox should survive roundtrip:\n") + content));
}

void OrgBackendExternalTest::testLogbookDrawerSurvivesRoundtrip()
{
    const QString orgContent = QStringLiteral(
        "* TODO Review code\n"
        "  :PROPERTIES:\n"
        "  :ID:       logbook-test-1\n"
        "  :END:\n"
        "  :LOGBOOK:\n"
        "  CLOCK: [2024-01-15 Mon 09:00]--[2024-01-15 Mon 10:30] =>  1:30\n"
        "  CLOCK: [2024-01-14 Sun 14:00]--[2024-01-14 Sun 15:00] =>  1:00\n"
        "  :END:\n"
        "Some notes about the review\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    // Description should have the prose but not the LOGBOOK
    QVERIFY2(inc->description().contains(QStringLiteral("Some notes about the review")),
             qPrintable(QStringLiteral("Description should contain prose: ") + inc->description()));
    QVERIFY2(!inc->description().contains(QStringLiteral("CLOCK:")),
             qPrintable(QStringLiteral("Description should NOT contain LOGBOOK entries: ") + inc->description()));

    // Store back
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    // Read file and verify LOGBOOK survived
    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral(":LOGBOOK:")),
             qPrintable(QStringLiteral("LOGBOOK drawer opening should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("CLOCK: [2024-01-15 Mon 09:00]--[2024-01-15 Mon 10:30]")),
             qPrintable(QStringLiteral("CLOCK entries should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral(":END:")),
             qPrintable(QStringLiteral("Drawer :END: should survive roundtrip:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("Some notes about the review")),
             qPrintable(QStringLiteral("Prose should survive alongside LOGBOOK:\n") + content));
}

void OrgBackendExternalTest::testDescriptionChangePreservesStructural()
{
    const QString orgContent = QStringLiteral(
        "* TODO Document feature\n"
        "  :PROPERTIES:\n"
        "  :ID:       desc-change-test-1\n"
        "  :END:\n"
        "Original description\n"
        "#+BEGIN_SRC shell\n"
        "make test\n"
        "#+END_SRC\n"
        "- [ ] Write tests\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    // Modify the description (triggers hash mismatch on write-back)
    inc->setDescription(QStringLiteral("Updated description text"));

    // Store back
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    // Read file and verify structural content survived despite description change
    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("Updated description text")),
             qPrintable(QStringLiteral("Updated description should appear:\n") + content));
    QVERIFY2(!content.contains(QStringLiteral("Original description")),
             qPrintable(QStringLiteral("Original description should be replaced:\n") + content));

    QVERIFY2(content.contains(QStringLiteral("#+BEGIN_SRC shell")),
             qPrintable(QStringLiteral("Source block should survive description change:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("make test")),
             qPrintable(QStringLiteral("Source block content should survive:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("#+END_SRC")),
             qPrintable(QStringLiteral("Source block END should survive:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("- [ ] Write tests")),
             qPrintable(QStringLiteral("Checkboxes should survive description change:\n") + content));
}

void OrgBackendExternalTest::testMultilineDescriptionRoundtrip()
{
    const QString orgContent = QStringLiteral(
        "* TODO Multi-line note\n"
        "  :PROPERTIES:\n"
        "  :ID:       multiline-desc-1\n"
        "  :END:\n"
        "First line of description\n"
        "Second line of description\n"
        "Third line of description\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    QVERIFY(inc->description().contains(QStringLiteral("First line")));
    QVERIFY(inc->description().contains(QStringLiteral("Second line")));
    QVERIFY(inc->description().contains(QStringLiteral("Third line")));

    // Store back
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("First line of description")),
             qPrintable(QStringLiteral("First description line should survive:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("Second line of description")),
             qPrintable(QStringLiteral("Second description line should survive:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("Third line of description")),
             qPrintable(QStringLiteral("Third description line should survive:\n") + content));
}

void OrgBackendExternalTest::testOrgzlyStyleRoundtrip()
{
    const QString orgContent = QStringLiteral(
        "* TODO Buy groceries\n"
        "  :PROPERTIES:\n"
        "  :ID:       orgzly-test-1\n"
        "  :CREATED_AT: [2024-06-15 Sat 08:30]\n"
        "  :LAST_REPEAT: [2024-07-01 Mon 09:00]\n"
        "  :END:\n"
        "  SCHEDULED: <2024-07-15 Mon>\n"
        "Remember to check prices\n"
    );

    QString calendarId = createOrgFile(orgContent);

    OrgBackend backend(m_tempDir->path());
    auto *fetchOp = backend.fetchItems(calendarId);
    QTRY_VERIFY_WITH_TIMEOUT(fetchOp->isFinished(), 5000);
    QCOMPARE(fetchOp->state(), SyncOperation::Succeeded);

    auto fetched = fetchOp->fetchedItems();
    QCOMPARE(fetched.size(), 1);
    auto inc = fetched.first();

    QVERIFY(inc->description().contains(QStringLiteral("Remember to check prices")));

    // Store back
    auto *pushOp = backend.pushItems(calendarId, {inc}, TranscodingPlan{});
    QTRY_VERIFY_WITH_TIMEOUT(pushOp->isFinished(), 5000);
    QCOMPARE(pushOp->state(), SyncOperation::Succeeded);

    QString filePath = m_tempDir->filePath(calendarId + QStringLiteral(".org"));
    QFile file(filePath);
    QVERIFY(file.open(QIODevice::ReadOnly | QIODevice::Text));
    QString content = QString::fromUtf8(file.readAll());
    file.close();

    QVERIFY2(content.contains(QStringLiteral("CREATED_AT")),
             qPrintable(QStringLiteral("Orgzly CREATED_AT property should survive:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("LAST_REPEAT")),
             qPrintable(QStringLiteral("Orgzly LAST_REPEAT property should survive:\n") + content));
    QVERIFY2(content.contains(QStringLiteral("Remember to check prices")),
             qPrintable(QStringLiteral("Description should survive:\n") + content));
}

QTEST_GUILESS_MAIN(OrgBackendExternalTest)
#include "tst_orgbackend_external.moc"
